// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: client_side.proto

//包名

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义发送请求信息
type ClientSideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 定义发送的参数
	// 参数类型 参数名 标识号(不可重复)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientSideRequest) Reset() {
	*x = ClientSideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_side_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSideRequest) ProtoMessage() {}

func (x *ClientSideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_side_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSideRequest.ProtoReflect.Descriptor instead.
func (*ClientSideRequest) Descriptor() ([]byte, []int) {
	return file_client_side_proto_rawDescGZIP(), []int{0}
}

func (x *ClientSideRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 定义响应信息
type ClientSideResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientSideResp) Reset() {
	*x = ClientSideResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_side_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSideResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSideResp) ProtoMessage() {}

func (x *ClientSideResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_side_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSideResp.ProtoReflect.Descriptor instead.
func (*ClientSideResp) Descriptor() ([]byte, []int) {
	return file_client_side_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSideResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_client_side_proto protoreflect.FileDescriptor

var file_client_side_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x0a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x64, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_side_proto_rawDescOnce sync.Once
	file_client_side_proto_rawDescData = file_client_side_proto_rawDesc
)

func file_client_side_proto_rawDescGZIP() []byte {
	file_client_side_proto_rawDescOnce.Do(func() {
		file_client_side_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_side_proto_rawDescData)
	})
	return file_client_side_proto_rawDescData
}

var file_client_side_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_side_proto_goTypes = []interface{}{
	(*ClientSideRequest)(nil), // 0: pb.ClientSideRequest
	(*ClientSideResp)(nil),    // 1: pb.ClientSideResp
}
var file_client_side_proto_depIdxs = []int32{
	0, // 0: pb.ClientSide.ClientSideHello:input_type -> pb.ClientSideRequest
	1, // 1: pb.ClientSide.ClientSideHello:output_type -> pb.ClientSideResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_side_proto_init() }
func file_client_side_proto_init() {
	if File_client_side_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_side_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_side_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSideResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_side_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_side_proto_goTypes,
		DependencyIndexes: file_client_side_proto_depIdxs,
		MessageInfos:      file_client_side_proto_msgTypes,
	}.Build()
	File_client_side_proto = out.File
	file_client_side_proto_rawDesc = nil
	file_client_side_proto_goTypes = nil
	file_client_side_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientSideClient is the client API for ClientSide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientSideClient interface {
	//一个ClientSideHello的方法
	ClientSideHello(ctx context.Context, opts ...grpc.CallOption) (ClientSide_ClientSideHelloClient, error)
}

type clientSideClient struct {
	cc grpc.ClientConnInterface
}

func NewClientSideClient(cc grpc.ClientConnInterface) ClientSideClient {
	return &clientSideClient{cc}
}

func (c *clientSideClient) ClientSideHello(ctx context.Context, opts ...grpc.CallOption) (ClientSide_ClientSideHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClientSide_serviceDesc.Streams[0], "/pb.ClientSide/ClientSideHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientSideClientSideHelloClient{stream}
	return x, nil
}

type ClientSide_ClientSideHelloClient interface {
	Send(*ClientSideRequest) error
	CloseAndRecv() (*ClientSideResp, error)
	grpc.ClientStream
}

type clientSideClientSideHelloClient struct {
	grpc.ClientStream
}

func (x *clientSideClientSideHelloClient) Send(m *ClientSideRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientSideClientSideHelloClient) CloseAndRecv() (*ClientSideResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientSideResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientSideServer is the server API for ClientSide service.
type ClientSideServer interface {
	//一个ClientSideHello的方法
	ClientSideHello(ClientSide_ClientSideHelloServer) error
}

// UnimplementedClientSideServer can be embedded to have forward compatible implementations.
type UnimplementedClientSideServer struct {
}

func (*UnimplementedClientSideServer) ClientSideHello(ClientSide_ClientSideHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientSideHello not implemented")
}

func RegisterClientSideServer(s *grpc.Server, srv ClientSideServer) {
	s.RegisterService(&_ClientSide_serviceDesc, srv)
}

func _ClientSide_ClientSideHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientSideServer).ClientSideHello(&clientSideClientSideHelloServer{stream})
}

type ClientSide_ClientSideHelloServer interface {
	SendAndClose(*ClientSideResp) error
	Recv() (*ClientSideRequest, error)
	grpc.ServerStream
}

type clientSideClientSideHelloServer struct {
	grpc.ServerStream
}

func (x *clientSideClientSideHelloServer) SendAndClose(m *ClientSideResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientSideClientSideHelloServer) Recv() (*ClientSideRequest, error) {
	m := new(ClientSideRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ClientSide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClientSide",
	HandlerType: (*ClientSideServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientSideHello",
			Handler:       _ClientSide_ClientSideHello_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client_side.proto",
}
